Elevator
Eaglestrike/2023-second-robot pull request #19
Opened 2023-08-29 23:48 UTC by Versus7

This PR is for feedback.

2023-09-30 20:34 UTC, linc-mvla requested changes
math wrong

2023-09-30 20:34 UTC, linc-mvla commented on src/main/cpp/Elevator/FeedforwardPID.cpp
> +    double velocity_time = (max_distance_ - max_velocity * acceleration_time) / max_velocity;
Check if the v*t term should be doubled

2023-09-30 20:34 UTC, linc-mvla commented on src/main/cpp/Elevator/FeedforwardPID.cpp
> +    velocity_time = velocity_time < 0 ? 0.0 : velocity_time;
You should probably deal with the triangle vs trapezoid profile here with an if statement instead of a ternary expression

2023-09-30 20:34 UTC, linc-mvla commented on src/main/cpp/Elevator/FeedforwardPID.cpp
Combine reversed and max_distance to just displacement double; treat logic within code

2023-09-30 20:34 UTC, linc-mvla commented on src/main/cpp/Elevator/FeedforwardPID.cpp
try precomputing values

2023-10-01 01:04 UTC, linc-mvla requested changes
NO

2023-10-01 01:04 UTC, linc-mvla commented on src/main/cpp/Elevator/FeedforwardPID.cpp
> +    double velocity_time = (max_distance_ - max_velocity * acceleration_time) / max_velocity;
nvm ur good

2023-10-01 01:04 UTC, linc-mvla commented on src/main/cpp/Elevator/FeedforwardPID.cpp
> +    return kp * (expected.velocity - current.velocity) + kd * (expected.position - current.position);
swapped

2023-10-01 01:04 UTC, linc-mvla commented on src/main/cpp/Elevator/FeedforwardPID.cpp
> +        pose.position = first_phase_distance + second_phase_distance + third_phase_distance;
foregt to multiply by reversed for pos, vel, and acc for the entirety of this entire if statement block. You have done some of it, but clearly not all.

2023-10-01 01:04 UTC, linc-mvla commented on src/main/cpp/Elevator/Elevator.cpp
> +    if (ElevatorConstants::MAX_ELEVATOR_EXTENSION - left_position < ElevatorConstants::POSITION_ERROR_TOLERANCE) {
take abs

2023-10-01 01:04 UTC, linc-mvla commented on src/main/cpp/Elevator/Elevator.cpp
> +    if (ElevatorConstants::MAX_ELEVATOR_EXTENSION - left_position < ElevatorConstants::POSITION_ERROR_TOLERANCE) {
or reorder pos > max - padding

2023-10-01 01:04 UTC, linc-mvla commented on src/main/cpp/Elevator/Elevator.cpp
> +    current_state = new_state;
deal with switching in the middle of a path

2023-10-01 01:04 UTC, linc-mvla commented on src/main/cpp/Elevator/Elevator.cpp
> +void Elevator::start() {
implement this in code for moving

2023-10-06 16:37 UTC, jonathanhliu21 requested changes

2023-10-06 16:37 UTC, jonathanhliu21 commented on src/main/include/Elevator/Elevator.h
> +        void setMaxDistance(double distance);
You need methods to set any height of elevator, not just one maximum distance.

2023-10-06 16:37 UTC, jonathanhliu21 commented on src/main/include/Elevator/Elevator.h
> +        void setPIDConstants(double kp, double kd);
kI?

2023-10-06 16:37 UTC, jonathanhliu21 commented on src/main/include/Elevator/Elevator.h
> +        void setState(ElevatorState new_state);
Shouldnt be able to set internal elevator state from outside elevator class (delete this)

2023-10-06 16:37 UTC, jonathanhliu21 commented on src/main/include/Elevator/Elevator.h
> +        double getRightRotation();
These aren't needed, just need method getting height of elevator. You should calculate this internally

2023-10-06 16:37 UTC, jonathanhliu21 commented on src/main/cpp/Elevator/FeedforwardPID.cpp
> +    double acceleration_time = max_velocity / max_acceleration;
check if max_acceleration and max_velocity are zero, otherwise numbers will just be NaN which is bad

2023-10-06 16:37 UTC, jonathanhliu21 commented on src/main/include/Elevator/FeedforwardPID.h
> +/**
Use Sunayna's trapezoial motion class once she is done with it

2023-10-06 16:37 UTC, jonathanhliu21 commented on src/main/cpp/Elevator/Elevator.cpp
> +    feedforward_.setMaxDistance(ElevatorConstants::MAX_ELEVATOR_EXTENSION); // while testing
These need to change as we want elevator to extend to any height between 0 and max height

2023-10-06 16:37 UTC, jonathanhliu21 commented on src/main/cpp/Elevator/Elevator.cpp
1. Rename `SetMaxDistance()` to `SetDistance()`
2. In `SetDistance()` check if the distance set is greater than the acutal max distance, and if so, ignore

2023-10-09 03:12 UTC, Versus7 commented
add KI term

2023-11-02 04:41 UTC, closed without merging