finish refactor
Eaglestrike/2023-second-robot pull request #2
Opened 2023-07-11 23:18 UTC by linc-mvla

refactored folders
it builds, but haven't tested
rework SwerveModule and SwerveDrive to look prettier

2023-07-12 02:58 UTC, jonathanhliu21 requested changes
small changes, not much besides deleting md files

2023-07-12 02:58 UTC, jonathanhliu21 commented on src/main/cpp/Robot.cpp
> +#include <Drive/DriveConstants.h>
Make this quotation include rather than angle brackets

2023-07-12 02:58 UTC, jonathanhliu21 commented on src/main/include/Climb/Climb.md
Dont' include MD files. Instead, have an explanation of the code in a Doxygen comment or on the README md.

2023-07-12 02:58 UTC, jonathanhliu21 commented on src/main/include/Drive/DriveConstants.h
Put this above pragma once statement

2023-07-12 02:58 UTC, jonathanhliu21 commented on src/main/include/GeneralConstants.h
> + * A file of constants
Change to "A file of *general* constants"

2023-07-12 02:58 UTC, jonathanhliu21 commented on src/main/include/Util/UtilConstants.h
> +/**
Put this above pragma statement.

2023-07-13 23:04 UTC, linc-mvla commented on src/main/cpp/Robot.cpp
> +#include <Drive/DriveConstants.h>
Isn't the folder in the local directory?

2023-07-14 03:03 UTC, jonathanhliu21 commented on src/main/cpp/Robot.cpp
> +#include <Drive/DriveConstants.h>
Yes, so quotations are preferred.

2023-08-05 22:17 UTC, jonathanhliu21 approved these changes
lgtm

2023-08-05 22:19 UTC, merged