Solve inversion
Eaglestrike/2023-second-robot pull request #4
Opened 2023-08-03 02:55 UTC by linc-mvla

makes the motor move the opposite way

2023-08-05 22:09 UTC, jonathanhliu21 requested changes
Main thing: don't use `inverted` for encoder inversion, that should still be used for wheel inversion (if applying positive voltage to wheel motor makes module move backwards). Instead, create a new member variable (perhaps `encoderInverted`) and use that for encoder inversions.

Also, for formatting, put spaces between operators and at the start of comments (i.e. `x = y + 1` instead of `x=y+1` and `// asdf` instead of `//asdf`); makes the code more readable

Currently about to board a flight (PIT -> SFO), may request further changes in the future

2023-08-05 22:09 UTC, jonathanhliu21 commented on src/main/cpp/Drive/SwerveModule.cpp
> +    : m_driveMotor{driveMotorId, "Drivebase"}, m_angleMotor{angleMotorId, "Drivebase"}, m_encoder{encoderId, "Drivebase"}, m_controller{kP, kI, kD},
Did the CAN ID change?

2023-08-05 22:09 UTC, jonathanhliu21 commented on src/main/cpp/Drive/SwerveModule.cpp
> -
Keep this, we still want to keep `m_inverted` original purpose (if positive voltage to wheel does not correspond to it moving in the positive direction)

2023-08-05 22:09 UTC, jonathanhliu21 commented on src/main/cpp/Drive/SwerveModule.cpp
> +    m_controller.Reset(); //Reset because integral and derivative terms will behave wonky
Can you explain (either here or in discord)?

2023-08-05 22:09 UTC, jonathanhliu21 commented on src/main/cpp/Drive/SwerveModule.cpp
> +  angleOutput *= m_inverted?-1.0:1.0; //If inverted, spin the turn motor in the opposite direction to the encoder PID
Instead of using `m_inverted`, use another variable (perhaps `m_encoderInverted` or something), see above for why

2023-08-05 22:09 UTC, jonathanhliu21 commented on src/main/cpp/Drive/SwerveModule.cpp
> +  double speed = m_flipped?-m_targetSpeed:m_targetSpeed; //if flipped, spin drive motor in opposite direction
Revert to original (see above for why)

2023-08-05 22:09 UTC, jonathanhliu21 commented on src/main/cpp/Drive/SwerveModule.cpp
> +  return angle1 > M_PI/2.0;
As long as you have tested this, this works because more efficient and fewer lines of code

2023-08-05 22:09 UTC, jonathanhliu21 commented on src/main/cpp/Robot.cpp
> +    m_navx = std::make_shared<AHRS>(frc::SerialPort::Port::kUSB);
Can you explain (either here or discord?)

2023-08-09 18:45 UTC, linc-mvla commented on src/main/cpp/Drive/SwerveModule.cpp
> +    m_controller.Reset(); //Reset because integral and derivative terms will behave wonky
If the motor is flipped, I flip the angle reading. I also reset the controller because it's basically changing it's setpoint.

2023-08-09 18:45 UTC, linc-mvla commented on src/main/cpp/Drive/SwerveModule.cpp
> +    m_controller.Reset(); //Reset because integral and derivative terms will behave wonky
I could've inverted the drive volts, but it does the same thing.

2023-08-10 23:29 UTC, merged